#define assemblatore asm
#define rottura break
#define caso case
#define cattura catch 
#define carattere char 
#define classe const 
#define continua continue
#define predefinito default
#define elimina delete
#define fai do
#define doppio double
#define altrimenti else
#define enumerazione enum
#define esterno extern
#define galleggiante float
#define per for 
#define amico friend
#define vaia goto
#define se if
#define inlinea inline 
#define intero int 
#define lungo long  
#define nuovo new 
#define privato private  
#define operatore operator  
#define protetto protected
#define pubblico public  
#define registra register 
#define ritorna return  
#define corto short  
#define segnato signed 
#define dimensionedi sizeof 
#define statico static 
#define struttura struct 
#define interrutore switch 
#define modello template 
#define questo this 
#define getta throw 
#define prova try 
#define definizionedeltipo typedef
#define unione union 
#define nonsegnato unsigned 
#define virtuare virtual 
#define vuoto void
#define volatile volatile
#define mentre while
#define principale main
#define stampa cout
#define salva cin
#define nomespazio namespace 
